### ISSUE TITLE
Reduce the bundle size

### ISSUE THREAD

**Issue by microchipgnu** [Mintbase/mintbase-ui#237]

**Comment by cif** [comment]
The best method identified was to purge much of the tailwindcss boilerplate.  This involves doing so for the components lib, but also then needing to include the a matching tailwindcss version / config for any consumers wishing to also use tailwind class names.

**Comment by cif** [comment]
Closing this as research task, in favor of next sprint 3[#272](https://github.com/Mintbase/mintbase-ui/issues/272)
